# Application
spring.application.name=HR Portal
server.port=8080

# Profile
spring.profiles.active=dev

# File Upload
file.upload-dir=uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# JWT
jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG
