package com.gentech.hrportal.repository;

import com.gentech.hrportal.entity.SalarySlip;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface SalarySlipRepository extends JpaRepository<SalarySlip, Long> {
    
    List<SalarySlip> findByEmployeeId(Long employeeId);
    
    Optional<SalarySlip> findByEmployeeIdAndMonthAndYear(Long employeeId, Integer month, Integer year);
    
    List<SalarySlip> findByCompanyIdAndMonthAndYear(Long companyId, Integer month, Integer year);
    
    List<SalarySlip> findByMonthAndYear(Integer month, Integer year);
    
    boolean existsByEmployeeIdAndMonthAndYear(Long employeeId, Integer month, Integer year);
    
    /**
     * Find all salary slips generated by a specific user
     * @param generatedById the generator user ID
     * @return list of salary slips
     */
    List<SalarySlip> findByGeneratedById(Long generatedById);
    
    /**
     * Find salary slip by ID with employee eagerly loaded
     * @param id the salary slip ID
     * @return optional salary slip with employee loaded
     */
    @Query("SELECT ss FROM SalarySlip ss JOIN FETCH ss.employee WHERE ss.id = :id")
    Optional<SalarySlip> findByIdWithEmployee(@Param("id") Long id);
}
